language: node_js
node_js:
- '0.10'
before_install:
- npm i -g gulp
env:
  global:
    secure: mgSBUgxhs9rgM6xR2oAkBAHfP4tcDnxYj55eYagadY2CEzDXu9TYZ/vifKotTgIEgeGYpQEqKBO02KTjz3+hG2vhud+Qs0Rly0blE5o9YseY/8rFwH/lgR5qr1vzdq4mZNiFj7G+Ys6sFaqFoKHnjFCFxcTuFk3JmP57mSefJfA=
before_script:
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
script: gulp
branches:
  only:
  - master
after_success:
  - gulp deploy
