language: node_js
node_js:
- '0.10'
before_install:
- npm i -g gulp
scripts: gulp
branches:
  only:
  - master
env:
  global:
    secure: mgSBUgxhs9rgM6xR2oAkBAHfP4tcDnxYj55eYagadY2CEzDXu9TYZ/vifKotTgIEgeGYpQEqKBO02KTjz3+hG2vhud+Qs0Rly0blE5o9YseY/8rFwH/lgR5qr1vzdq4mZNiFj7G+Ys6sFaqFoKHnjFCFxcTuFk3JmP57mSefJfA=
after_success:
  - gulp deploy
